-- AlterTable
ALTER TABLE "User" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "energy" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN     "fullRegen" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "gold" INTEGER NOT NULL DEFAULT 100;
